name: Build

on:
  push:
    branches: [main]
    paths:
      - 'NamazuFlippers/**'
  pull_request:
    branches: [main]
    paths:
      - 'NamazuFlippers/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: NamazuFlippers/
    env:
      DALAMUD_HOME: /tmp/dalamud
    steps:
      - uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Download Dalamud
        run: |
          wget -q https://goatcorp.github.io/dalamud-distrib/latest.zip -O /tmp/dalamud.zip
          unzip -q /tmp/dalamud.zip -d $DALAMUD_HOME

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release --nologo
